src/strategies/contract-call/README.md, src/strategies/contract-call/index.ts, src/strategies/index.ts
Added contract-call strategy that allows any contract method to be used to calculate voter scores.
=> Add contract-call strategy

src/plugins/aragon/index.ts
- Remove `id` property from the token on the contract call.
- Add call to get the nonce variable from the contract, rather than the account nonce itself.
=> Aragon Plugin: Correct contract call, add call to get nonce

src/networks.json, src/utils.ts
Need to add the following in web3 to interact with Meter mainnet
const meterify = require(“meterify”).meterify;
const Web3 = require(“web3");
const web3 = meterify(new Web3(), “https://rpc.meter.io”);
Fixes # .
adding meter main net network information and multicall contract address
The meterify library can be found in https://github.com/meterio/meterify
- 
-
=> Please add Meter.io mainet information

src/strategies/index.ts, src/strategies/mithcash/examples.json, src/strategies/mithcash/index.ts
- Added a strategy that calculates the user's voting power based on the balance of MIS tokens and the amount of tokens staked in boardroom and provided liquidity in Sushiswap.
=> Add mithcash strategy

src/strategies/index.ts, src/strategies/staked-keep/README.md, src/strategies/staked-keep/examples.json, src/strategies/staked-keep/index.ts
As the title says, this PR just adds a strategy that counts the number of KEEP tokens staked by an address.
I forked it from the `uniswap` strategy and tested it with `npm run test --strategy=staked-keep`.
=> Add Staked KEEP

src/strategies/work/examples.json, src/strategies/work/index.ts
Revises `work` strategy to match [original spec](https://hackmd.io/Z1Wg7AzgS5qTDsREZ84Yxw)
- Adds 1 vote for non-staking whitelisted addresses
- Adds quadratic vote calculation for staked tokens
- Updates xDAI test examples, including staking contract address and an address with staked tokens
=> Update work strategy

src/strategies/index.ts, src/strategies/sushiswap/examples.json, src/strategies/sushiswap/index.ts
Hello! 
This is a PR to add a sushiswap LP token strategy to enable sushi liquidity providers to accurately participate in snapshot voting. 
It has not been confirmed to work, please review.
=> Add Sushiswap LP token strategy

src/strategies/index.ts, src/strategies/masterchef/examples.json, src/strategies/masterchef/index.ts, src/strategies/sushiswap/examples.json
This PR adds a strategy that allows users with their LP tokens staked in Sushi's masterchef to vote in snapshot proposals.
Note: this has not been tested and I'm not entirely familiar with The Graph and its inner workings. Please review and confirm it works however possible.
If there are any changes that need to be made, let me know! Thank you!
=> Add Sushi Masterchef LP token strategy

src/strategies/frax-finance/examples.json, src/strategies/frax-finance/index.ts, src/strategies/index.ts, test/index.ts
This allows Frax Finance to calculate FXS balances from free FXS tokens, as well LP tokens, both free and staked. It gives more weight to LP tokens that are staked for longer periods of time.
=> Add Frax Finance Strategy to account for FXS in LP tokens

src/plugins/gnosis/index.ts
- Add `pairsTokensInverted` query for token inverted pairs.
- Fix `network` type from number to string.
=> Add Uniswap inverted pairs query on Gnosis plugin

src/strategies/index.ts, src/strategies/tokenlon/examples.json, src/strategies/tokenlon/index.ts
Add tokenlon stratrgy
LON phase 2 liquidity mining:
https://tokenlon.zendesk.com/hc/en-us/articles/360055773831-Tutorial-of-the-2nd-phase-of-LON-liquidity-mining
Relative contracts:
[Uniswap LON-ETH pair](https://etherscan.io/address/0x7924a818013f39cf800f5589ff1f1f0def54f31f#readContract)
[SushiSwap LON-USDT pair](https://etherscan.io/address/0x55d31f68975e446a40a2d02ffa4b0e1bfb233c2f#readContract)
[Uniswap StakingRewards contract](https://etherscan.io/address/0x929CF614C917944dD278BC2134714EaA4121BC6A#readContract)
[SushiSwap StakingMultiRewards contract](https://etherscan.io/address/0x11520d501E10E2E02A2715C4A9d3F8aEb1b72A7A#readContract)
Strategy:
```
user's voting power = LON balance of user +  
(users' LP token + users' LP token staked in Uniswap StakingRewards contract) / LP total …
```
=> Add tokenlon strategy

src/strategies/dittomoney/examples.json, src/strategies/dittomoney/index.ts
Upgrade Ditto Strategy 
-  add CafeSwap Balance
-  add JetFuel Vaults
-  add Autorfarm Balance
**npm run test --strategy=dittomoney**
```console
> @snapshot-labs/snapshot.js@0.1.6 test
> node test/index.ts
Strategy: "dittomoney"
Ditto.money
[
{
'0x614812d04526C0C882A6cB993a135fcD559F33F9': 3423.997380018601,
'0xff91AcCd5277cc3de3E73DD77e3102b1980e439e': 1031512744857019.1,
'0x05ff2b0db69458a0750badebc4f9e13add608c7f': 0,
'0xd1a8Dd23e356B9fAE27dF5DeF9ea025A602EC81e': 0.000104180662529254,
'0x48f7cb174a2333de834452ad240ce8d3d827dc55': 1.130252e-11,
'0x0d3cae1ff719d6a2ac0fcd7cd22f599cac64b6ec': 59.320683326386295,
'0xE0e710A907a8E44c078e6212Efa336C1191F4CD1': 1.130252e-11
}
]
getScores: 3.504s
=> feat(ditto-money): add power vote for cafeswap, jetFuel vault and autofarm

src/strategies/index.ts, src/strategies/rebased/examples.json, src/strategies/rebased/index.ts
- voting power for staking users
- voting power for users who hold the RebasedV2 token
**npm run test --strategy=rebased**
```console
Strategy: "rebased"
Rebased
[
{
'0xde389fb34f54bec6d09bd98152a69be15c43163f': 4.326101359e-9,
'0xbe80fd79e26ce0a605e5d2803e876f1b009d70cc': 2.20359154e-10,
'0x55c307cbe54a1c1c105838a9d0fd60b75d7ff951': 1.3811117e-11,
'0x01BaD7E976d59CE92295Dbacd5da7fc06FE05412': 0,
'0x64be824f732312490224a67537d49b8580068abf': 7.6433702889e-8
}
]
getScores: 4.923s
```
=> feat(strategies): add Rebased strategy

src/networks.json
the trailing flash typo display a 404 for users
Fixes # .
- remove trailing slash
- 
-
=> remove trailing slash

src/strategies/curio-cards-erc20-weighted/README.md, src/strategies/curio-cards-erc20-weighted/examples.json, src/strategies/curio-cards-erc20-weighted/index.ts, src/strategies/index.ts
This is a strategy for Curio Cards, an early NFT trading cards
project from 2017.
Curio Cards predates the erc721 and erc1155 NFT specifications.
Each card is implemented as an erc20 with a max supply between
100-2000 tokens. This strategy weights the vote according to the
address's holdings of each card multiplied by the relative
scarcity of each card.
This might be one of the heavier strategies as it queries 30
different token contracts. The query is performed in parallel.
Test run output: https://gist.github.com/fafrd/5751bc61b0ba3b9a4288d933f1c3410d
=> Create curio.cards voting strategy 0.1.0

package-lock.json, package.json, src/plugins/quorum/index.ts
Since the Vue plugin may pass the snapshot block number as a string, the standard `typeof snapshot === 'number' ? snapshot : 'latest'` check would've overridden it to `'latest'`. In this PR, this check was improved to check first for an explicit `'latest'` value and try to parse it using `toNumber` otherwise.
=> Improve support for numerical snapshot block numbers

package.json
Fixes:
```ts
import snapshot from '@snapshot/snapshot.js'
```
Without type declaration file, import `@snapshot/snapshot.js` directly would cause an error:
```shell
Could not find a declaration file for module '@snapshot-labs/snapshot.js'. 
'/Users/zhouhancheng/code/Maskbook/node_modules/.pnpm/@snapshot-labs/snapshot.js@0.1.7/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js' 
implicitly has an 'any' type.
```
=> chore: add type declaration

src/strategies/tokenlon/examples.json, src/strategies/tokenlon/index.ts
Users could gain more LON if they have xLON shares. This PR calculates the voting power of xLON contract.
Relative feature:
https://tokenlon.im/lon/staking
Run tests:
```
npm run test --strategy=tokenlon
```
Result:
```
Strategy: "tokenlon"
Tokenlon
[
{
'0x39422F5065cF7968242747Bc19e812B6Ae98B50F': 0,
'0x3e2764be2a583bab5589223cafabd78c2f9419cf': 59.69314550334276,
'0x77a6ece6eb5a8d54d1b643f03beebad7e6c6ff06': 20640.785595376157,
'0x50a01818f24435f965b09ea8fa80826e4355bed5': 16.20886407601014
}
]
getScores: 5.132s
```
=> Calculate LON shares in xLON contract

src/strategies/index.ts, src/strategies/pob-hash/examples.json, src/strategies/pob-hash/index.ts
Fixes `pob-hash`:
- Changes subgraph to new subgraph
- Utilizes an address map, to retain original casing of address provided
- Renames to `pob-hash` and removes cv mechanics from strategy
=> [Urgent] Bug fixes to pob-hash strategy

src/networks.json
- RPC server for RSK Testnet has a typo, fixing this
=> Typo in RSK Testnet rpc server url

src/networks.json
Fixes # .
Since HECO only support ```https://mainnet.heco.vote``` to get archived data, we have to use the vote rpc as snapshot rpc url
- update heco testnet rpc
- update heco mainnet explorer
- update heco mainnet rpc
- update heco mainnet ws
- update heco mainnet explorer
=> fix: update heco mainet rpc url

src/strategies/index.ts, src/strategies/xseen/examples.json, src/strategies/xseen/index.ts
Creates strategy to derive the SEEN value from the amount of xSEEN tokens held by an address at the time of the Snapshot
The strategy will be relevant to the https://snapshot.org/#/seen workspace
=> xSEEN Strategy for seen.haus

src/strategies/masterchef-pool-balance/index.ts
strategy didn't multiply by weight when `uniPairAddress` is `null`
Fixes # .
- fix strategy code
- 
-
=> strategies/masterchef-pool-balance: (fix) weight

src/strategies/balancer/examples.json, src/strategies/balancer/index.ts
- Add queries to the Balancer V2 subgraph
- Updates V1 subgraph queries to target the "balancer" subgraph instead of the "balancer-beta" one
- Add examples.json to validate balances; the final address in addresses[] has an account with Balancer V2 pool tokens holding BAL
=> Add support for tokens in Balancer V2 pools

src/strategies/decentraland-estate-size/index.ts
Handle empty results from the graph
=> Fix: handle empty results on [decentraland-estate-size]

src/strategies/index.ts, src/strategies/inverse-xinv/README.md, src/strategies/inverse-xinv/examples.json, src/strategies/inverse-xinv/index.ts
This is a PR to add a new strategy to snapshot that allows support for staked INV within Anchor, referred to as xINV.
A good portion of the INV supply is staked in Anchor, so it would be fantastic if this could be added :smiley:
=> [inverse-xinv] Inverse xINV strategy

src/strategies/masterchef-pool-balance/examples.json, src/strategies/masterchef-pool-balance/index.ts
- The `masterchef-pool-balance` strategy could benefit from the use of non integer values. Since `BigNumber` has to be integer we added a `weightDecimals` variable to make final calculations.
=> [masterchef-pool-balance] ability to have non integer weights

src/networks.json
Fixes # .
- Current rpc node isn't a full sync node, which will cause ""missing trie node" issue, try this new added node provided by Heco community.
=> Add a full sync node for Heco chain

src/plugins/daoModule/index.ts
-  If DAO Module has minimum bond set to zero, a default bond of 0.001 ETH is going to be set
=> Fix: Handle edge case when dao module minimum bond is zero

src/strategies/aave-governance-power/README.md, src/strategies/aave-governance-power/examples.json, src/strategies/aave-governance-power/index.ts, src/strategies/index.ts
- Add a new strategy named `aave-governance-power` for Snapshot to be able to track `Voting power` or `Proposition power` of an address from GovernanceStrategy contract for tracking any governance that derives from an Aave Governance V2 contract.
=> [aave-governance-power] feat: Add Aave Governance strategy

src/strategies/aave-governance-power/index.ts
Fixes "Oops, failed to check voting power" when passing "latest"  to the snapshot argument variable at the `aave-governance-power`  strategy.
- Get block number if "latest" is passed to snapshot argument.
=> fix: support "latest" snapshot at aave-governance-power strategy

test/index.spec.ts
Fixes issue when running `uniswap` strategy,
where
`0x79317fC0fB17bC0CE213a2B50F343e4D4C277704` is the output 
and `0x79317fc0fb17bc0ce213a2b50f343e4d4c277704` is given in example.json
=> Test cases failing if addresses are different word case

src/strategies/eth-balance/examples.json, src/strategies/eth-with-balance/README.md, src/strategies/eth-with-balance/examples.json, src/strategies/eth-with-balance/index.ts, src/strategies/index.ts
Adds a new strategy `eth-with-balance` which gives a voting power of 1 to any address with a configurable minimum ETH balance.
=> [eth-with-balance] Add eth-with-balance strategy

src/strategies/balancer-smart-pool/index.ts
Updates #303
I made the assumption that Snapshot had all `addresses` before calling the strategy. This update checks total supply of the pool shares token in the calculation instead of using the sum of shares owned by `addresses`
=> [balancer-smart-pool] update balancer-smart-pool strategy to compare weights to total supply

src/networks.json
Introduce additional RPC address for Fantom Opera network.
The new RPC is https://rpc.ftm.tools which is an RPC aggregator, widely used in Fantom Opera project and by Fantom Opera users.
It has become very popular during the high load period on Fantom, which caused the main RPC to lag and fail to respond at all.
=> Add new RPC - rpc.ftm.tools for Fantom Opera blockchain

src/plugins/safeSnap/index.ts
There is an issue that is triggered when loading this page for a second time here: https://snapshot.org/#/samuv.eth/proposal/QmUKuzPSL1zoJxdNVGbHCGvjWKxdQZGpLrR9VWShv4dpqa
On this PR i do a small fix by making the chainId directly available.
=> Fix: don't load chainId from provider

package.json
Fixes `ReferenceError: TextDecoder is not defined`
A lot of users reporting this error if npm installs version above `^2.5.3`, this fix will restrict to install only version `2.5.3` where we are not getting this error
=> ReferenceError: TextDecoder is not defined

src/strategies/erc721-with-tokenid/README.md, src/strategies/erc721-with-tokenid/examples.json, src/strategies/erc721-with-tokenid/index.ts, src/strategies/index.ts
Add Strategy for ERC721 token with a specified tokenId. Useful for POAPs to allow voting with a specified ID rather than all.
=> [erc721-with-tokenid] Add ERC721 with tokenid strategy

src/networks.json
When using the Moonbase Alpha network with Snapshot, we realized that we couldn't vote.
After doing some digging, we found that the issue was occurring when calling the `aggregate` function.
We have gone ahead and deployed a new `Multicall` contract (you can find the verified code [here](https://moonbase-blockscout.testnet.moonbeam.network/address/0xf09FD6B6FF3f41614b9d6be2166A0D07045A3A97/contracts)).
=> fix: update `Multicall` contract

.github/workflows/npm-publish.yml
Add `NPM_TOKEN` to [github secrets ](https://docs.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
To publish a new version:
- Update version number in package.json
- Publish a new release on github by going here https://github.com/snapshot-labs/snapshot.js/releases/new?title=v0.3.35&tag=v0.3.35 (new version tag and title)
=> Github workflow to autopublish on NPM

src/networks.json
Fixes # .
- network id 7341 shyft mainnet
- network id 11437 shyft testnet
- have also deployed multicall to these:
- http://bx.shyft.network/address/0xceb10e9133D771cA93c8002Be527A465E85381a2/contracts
http://bx.testnet.shyft.network/address/0x407159bAA564dA0c3b14D1215d8E2654cEEE73F4/contracts
=> Add shyft mainnet and testnet

package.json, src/networks.json
Reverts snapshot-labs/snapshot.js#521 as node is not a full archive node and `0.3.55` is not released yet
=> Revert #521

package.json, src/schemas/proposal.json
Proposal creation is failing because of format URL. Reverting this change as there doesn't seem to be a way to fix it quickly.
=> Remove format uri because it's causing proposal creation to fail

src/schemas/proposal.json, src/utils.ts
Fixes bug where we couldn't validate URL and empty string for discussion. Also add some URl types like `snapshot://` that we might want to use in the future.
=> Add customUrl format validation and use for discussion

src/networks.json
Fixes # .
Pull request to add Klaytn testnet Baobab (network_id 1001) to Snapshot
- Added klaytn network to networks.json
- See [https://www.klaytn.com/](https://www.klaytn.com/)
=> Add klaytn testnet baobab node

src/sign/utils.ts
Originally, the call to /api/msg would throw "invalid signature string; must be 65 bytes" if the signature has a different length or throw rsv errors, if the 1271 sig is 65 bytes long.
The 1271 signatures of Ambire Wallet have different length and verifying a message would throw errors.
this PR solved this issue, ensuring message verification works on smart wallets like Ambire, Gnosis Safe, Argent, etc
=> fix: Supporting 1271 signatures not being 65 bytes long nor rsv compatible

package.json, src/utils/provider.ts
Reference:
https://docs.ethers.io/v5/api/providers/jsonrpc-provider/
> if no network is specified, it will be determined automatically by querying the node using eth_chainId and falling back on eth_networkId.
We already know the network
So this will reduce one call to brovider `eth_chainId` every time someone opens snapshot.org
=> Pass network to provider

src/networks.json
Adds Boba's Avalanche L2 to the network list.
Official Docs link: https://docs.boba.network/for-developers/network-avalanche#boba-avalanche-l2-43288-for-the-avalanche-l1-43114
=> Add Boba L2 (Avalanche) Network

src/schemas/space.json
Partially fixes [2844 for Snapshot](https://github.com/snapshot-labs/snapshot/issues/2844).
**Background**
Currently the actions of creating a new proposal and casting a vote require a signature each time. The goal is to add new space setting enabling using the alias.
A sister PR on snapshot repo will implement the logic in the front end, this one updates the schema for spaces.
**Changes proposed in this pull request:**
- add `aliased: boolean` to `space.voting`
=> Schema update: add aliased to space settings for voting and proposals

package.json, src/networks.json
Fixes partially [blockfinder/70](https://github.com/snapshot-labs/blockfinder/issues/70)
**Background**
Explained [here](https://github.com/snapshot-labs/blockfinder/pull/176)
**Changes proposed in this pull request:**
- restructure `explorer` key for networks to cater for urls which are not callable APIs
:warning: definitely needs a second pair of eyes to catch typos
**Related PRs**
- [blockfinder](https://github.com/snapshot-labs/blockfinder/pull/176)
- snapshot
=> Add apiUrl to networks explorer

package.json, src/networks.json
Following the request from Moonbeam team to update their explorer url 🙏
=> Moonbeam: update explorer url

src/utils/provider.ts
Fixes #810.
- Turn on GZip compression by default for all requests by all Providers.
=> Turn on GZip compression by default

package.json, src/utils.ts
Creating ajv instance is expensive, around ~11ms of synchronous execution on my machine. This is where most of `validateSchema`'s runtime is spent, which is executed twice per vote, resulting in 22ms of execution time spent creating fresh ajv instances on every vote.
Reusing ajv instance lowers validation time to ~0.02ms, 500x improvement.
It makes sense to precompute `.compile` as well, but those improvements seem negligible in our current usage.
=> refactor: reuse ajv instance

src/schemas/space.json
The `delegation` wasn't used are far as I can tell, so I removed it as well.
=> feat: Add space delegation portal schema

src/networks.json
- Added Evmos testnet and mainnet
- Note: block height does not start at 1 (security hardfork at launch)
- Cascadia's testnet chainID is incorrect (fork of Evmos)
- Changed Cascadia's testnet chainid thats listed on other block explorers
- Multicall contracts verified on Sourcify
=> Add Evmos Testnet and Mainnet

src/networks.json
1. Added Findora mainnet
2. The previous PR: https://github.com/snapshot-labs/snapshot.js/pull/786
3. Fixed the last remaining issue, the NODE LIMIT (see test result in the screenshot attached) is now > 500
Hi, @ChaituVR, I wanted to express my gratitude for your continuous technical support throughout this process. We have invested significant engineering efforts and successfully resolved the final NODE LIMIT issue. As per our previous conversation, I was hoping you could assist us by merging the PR now that it's been addressed.
=> Added Findora network

package.json, src/networks.json
Related to [4063](https://github.com/snapshot-labs/snapshot/pull/4063), follows up the explorer url change.
=> Gnosis - replace with working explorer endpoint

src/networks.json
The Testnet was reset and moved to Chain ID 1072. ID 1071 does not exist any longer. Submitted new Chain ID and Multical contract
Fixes # .
-  new Chain ID
- new Multicall contract
-
=> Update Chain ID Shimmer EVM Testnet in networks.json

package.json, src/sign/index.ts
- If signature is `0x` , it will use relayer instead of sequencer
- Should not break anything with existing flow
=> Fallback to relayer if signature is 0x

src/utils.ts, test/e2e/utils/getScores.spec.ts
When polling the score-api, any network errors will throw a `FetchError`, which is not handled by the SDK, making the caller rescue this error, in addition to handling JSON-RPC error.
The caller will have to handle 3 situations:
- success: a json rpc object, from Promise.resolve
- error on score-api: a json-rpc error object, from Promise.reject
- network error: a thrown Error
`getScores` should return only one response format on error, a json-rpc error.
After fix, the caller will have to handle 2 situations:
- success: a json rpc object, with Promise.resolve
- error: a json-rpc error object, from Promise.reject
Which simplify the error handling on the caller side, in addition of getting the error message.
- for all score-api requests, add a try/catch and return a json-rpc error object on …
=> fix: return the same json error on network error

package.json, src/networks.json
We are using a older version of multicall
=> fix: Update multicall for mumbai network

.github/workflows/test.yml
Run the github action tests on more node versions.
It's currently only ran on node 14, which is dead for many years.
Adding 16 (which is EOL but is still used by many of our services), 18 (current) and 20.
This will avoid scenario like https://github.com/snapshot-labs/snapshot.js/pull/904 which fails on node 18
=> chore: run CI tests on more node versions

src/networks.json
- remove trailing slashes of the links: "scope.com/" -> "scope.com"
=> Fix block explorer links of Klaytn

src/networks.json
These have the wrong chainID and key
=> Fix chain id for KardiaChain Mainnet and neon devnet

package.json, src/networks.json
Fixes https://github.com/snapshot-labs/pitches/issues/27
- remove unused networks
Removed networks 
```
[
"14",
"16",
"20",
"31",
"36",
"44",
"50",
"51",
"58",
"65",
"69",
"70",
"74",
"87",
"99",
"106",
"111",
"119",
"128",
"188",
"256",
"288",
"361",
"499",
"534",
"595",
"599",
"647",
"842",
"940",
"941",
"1234",
"1319",
"1701",
"1818",
"1819",
"2020",
"2611",
"4062",
"4690",
"5551",
"5851",
"7363",
"7700",
"9000",
"9052",
"11437",
"12321",
"12357",
"22040",
"32659",
"42262",
"43288",
"60001",
"70001",
"70002",
"70103",
"71401",
"71402",
"333888",
"333999",
"666666",
"888888",
"900000",
"278611351",
"11297108109",
"11297108099"
]
```
=> feat(networks): remove unused networks

package.json, src/schemas/space.json, src/schemas/zodiac.json, src/utils.ts, test/schema.spec.ts
- Add a new keyword `snapshotKeyword` to check if the network exists in networks.json or not
- If snapshot's env is `mainnet` it will check only mainnet networks
- if snapshot's env is `testnet` it will check only testnet networks
To Do: 
```js
validateSchema(schema, data, { snapshotEnv: 'mainnet' })
```
=> feat: Check if network is mainnet or testnet depending on env

src/utils.spec.js, src/utils.ts
From https://github.com/orgs/snapshot-labs/projects/12/views/7?pane=issue&itemId=43073796
The `validate` passes the arguments as is to score-api without check. There are some basic check possible from the SDK, to filter out invalid requests, and lighten the score-api server load.
This will also avoid log pollution on score-api, making the log more relevant
Fix #924
Add some basic argument validation on the SDK side, and return a meaningful error when argument are not valid.
- Add check that author address is valid
- Add check that network is not empty, and valid (referenced in networks.json)
- Check that the given `snapshot` is in the network range (should be greater than the network's `start` block)
- Check that `network` in strategies are valid
- Fully tests `validate`
- Send some …
=> fix: check for invalid arguments in `validate`

src/networks.json
Update smartbch rpc with more fallbacks
Fixes # single dependency on one RPC node which was offline, causing vote weight to not calculate properly
- Add addditional RPC endpoints for greater fallback
=> Update smartbch rpc with fallbacks

package.json, src/networks.json
Some networks are missing `start` param
=> fix: Add start param to network that missing it

package.json, src/voting/rankedChoice.ts
Right now, In ranked choice voting
we calculate the total voting power of all votes after all rounds, which is the same as total voting power of all votes anyway
This is causing problems with shutter, If we want to calculate total voting power after all rounds of RCV, we need all choices to be decrypted, so in this change we are just calculating total voting power of all votes like all other voting types
=> fix: Ranked Choice total voting power

src/schemas/space.json
Related to https://github.com/snapshot-labs/snapshot-hub/issues/822
Right now it accepts even if user pass invalid objects like
```json
"boost":{}
```
```json
"boost": {
"disabled": true
}
```
```json
"boost":  {
"bribeDisabled": false
}
```
With this fix it will accept only if both fields are present, if we have `boost` object in settings,
so these will be valid
```json
{
"name": "Test",
"treasuries": [],
...
"boost": {
"disabled": false,
"bribeEnabled": false
}
}
```
```json
{
"name": "Test",
"treasuries": [],
....
// without boost object
}
```
=> fix: Add disabled and bribeEnabled as required fields inside boost object

src/schemas/space.json, src/sign/index.ts, test/examples/space.json
Related to https://github.com/snapshot-labs/snapshot/issues/4600
This will add ability to send a new space settings to store optimistic quorum (default to undefined)
- Run `yarn test` 
- Change values in `examples/space.json`
- Try passing different values to `quorumType` 
- If `quorumType` exist, It should accept only `optimistic` and reject all
=> feat: Add quorumType to space settings

package.json, src/sign/index.ts, test/test.html
- Right now if there is a network issue (internet issue or if sequencer/relayer is down, we couldn't show a error because of this
- This creates lot of confusions with safe voting, especially when it doesn't show any message while voting 
- It return following error 
- ![image](https://github.com/snapshot-labs/snapshot.js/assets/15967809/299440a7-d524-4be3-992e-0f0f74e71632)
- UI is stuck like this without any error
Use the newly added test.html to test signing when sequencer is not available 
- Run `yarn build` (without the fix)
- Run `serve -p 9000` 
- Go to  http://localhost:9000/test/test.html
- Try voting , and should return a Uncaught error
- Now with new fix run `yarn build`
- Run `serve -p 9000` 
- Go to  http://localhost:9000/test/test.html
- Try voting, and you see a caught …
=> fix: UI doesn't show any error if sequencer is down or unavailable

package.json, src/sign/index.ts
Right now sequencer sends a response object with an error, we have removed it here #981 as it is avoiding some errors like network errors
=> fix: Reject with json if request fails with json

package.json, src/delegationSubgraphs.json
Related to https://github.com/snapshot-labs/subgrapher/pull/35
=> fix: Update subgrapher delegation URLs

src/schemas/space.json
This allows for space settings to use `split-delegation` in their settings, which is the first step to integrating it into the Snapshot settings UI.
=> Add Split-Delegation to delegate portal options

package.json, src/utils.ts, test/e2e/utils/delegation.spec.ts
Add a new validatin rule for validating evm/starknet address
Inspired by how Argent X is validating starknet address https://github.com/argentlabs/argent-starknet-recover/blob/main/schema.ts#L43
=> feat: add support for starknet address

package.json, src/schemas/profile.json
Used in https://github.com/snapshot-labs/sx-monorepo/pull/394
Add `cover`, `twitter` and `github` to user profile
=> feat: add more fields to user profile

package.json, src/schemas/statement.json
Make the `about` property in Statement optional. 
This field is not used at all on SX
=> fix: make about field optional

package.json, src/schemas/statement.json
This PR removes `minLength` on `about` and `discourse` properties, thus allowing empty string as valid value.
=> Fix make about field optional

src/schemas/vote.json
This PR increase the max length of the vote reason to `1000`
=> fix: increase vote reason to 1000 chars

src/schemas/statement.json
Uppercase the Statement `status`
=> fix: uppercase statement status options

src/schemas/profile.json
Related to https://github.com/snapshot-labs/sx-monorepo/issues/406
Add `farcaster` and `lens` social network to user profile
=> feat: add lens and farcaster to user profile

src/utils.ts, test/e2e/utils/getScores.spec.ts, test/schema.spec.ts
Right now we call both the old resolver and the new resolver to get the text record,
which is causing this issue: https://discord.com/channels/955773041898573854/1030772407226601522/1260542812106002526
This change will get the resolver of the ENS name and use that resolver's text record
- call getSpaceController before and after the fix
```ts
snapshot.utils.getSpaceController('buzzedbears.eth', '1').then(console.log).catch(console.error);
```
=> fix: Use ENS name's resolver to get text record

src/constants.json, src/sign/index.ts
Right now it is `mainnet` in many places, so `livenet` keyword could be a cofusion
=> fix: Rename livenet to mainnet

package.json, src/verify/index.ts
Right now we only allow strings inside `domain` type, but in somecases, we do pass chainID as number: for example 
https://github.com/snapshot-labs/snapshot-relayer/blob/f6b8a4b8a22ef8c84da8a45b0d3d027635ee3d9e/src/api.ts#L32-L35
and 
https://github.com/snapshot-labs/snapshot.js/blob/921904924e6b671fa5392824b888f3180c780cf8/src/sign/index.ts#L86-L88
=> fix: Allow number inside domain

package.json, src/utils.spec.js, src/utils.ts
Fix https://snapshot-labs.sentry.io/issues/5639825201/?query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=15
This PR will handle error, and return `null` when the given ENS name is not valid
=> fix: handle error when the ens is not valid

package.json, src/utils/delegation.ts
With this change space can be passed as null and this will result in all delegates to be returned instead of per-space results only.
This will be used on new delegate-registry-api.
=> feat: allow getDelegatesBySpace to fetch delegates for all spaces

package.json, src/schemas/space.json
Working toward https://github.com/snapshot-labs/workflow/issues/152
This PR adds the `cover` property to the space settings, similar to the already existing one in Profile.
=> feat: add support for cover image in space

src/schemas/space.json
This change is similar to field `strategies`
=> fix: Restrict treasuries items to be unique

package.json, src/schemas/space.json, src/utils.ts, test/examples/space.json
From https://github.com/snapshot-labs/snapshot-sequencer/pull/439#discussion_r1773253485
This PR enforce that the `domain` property in space settings is a valid hostname, and always lowercase
=> fix: enforce lowecase valid hostname for space domain

package.json, src/schemas/space.json, src/utils.ts, test/examples/space.json
Towards https://github.com/snapshot-labs/workflow/issues/143
- Validation for labels
- Allows 100 labels with `id`, `name`, `description` and `color`
- Run `yarn test`
- Try changing values in test/examples/space.json
=> feat: Validation for labels

package.json, src/schemas/space.json, test/examples/space.json
Continued from https://github.com/snapshot-labs/snapshot.js/pull/1062
- To make it the same as GitHub
- Run `yarn test`
- Try changing values in test/examples/space.json
=> fix: Labels description field as optional

package.json, src/schemas/space.json
Fix https://github.com/snapshot-labs/sx-monorepo/pull/840
Allow starknet treasury address
=> fix: allow starknet treasury address

src/schemas/space.json, src/utils.ts, test/examples/space.json
This PR:
- add a new `evmAddress` validation, which accept checksummed and lowercase EVM address (existing `address` validation is only accepting checksummed address)
- Migrate existing regex address validation to use `evmAddress` 
- Migrate `delegationPortalNetwork` from `address` to `evmAddress` (this is used only on v2, which does not enforce checksummed address)
- Migrate recently treasuries address to also accept lowercase address
=> fix: loosen some address validation to accept lowercase

package.json, src/schemas/space.json, src/utils.ts, test/examples/space-starknet-delegation.json, test/examples/space.json, test/schema.spec.ts
Toward https://github.com/snapshot-labs/sx-monorepo/pull/851
Continuing https://github.com/snapshot-labs/snapshot.js/pull/1066#issuecomment-2399931257
This PR adds support for starknet addresses and network for delegations and treasuries
=> feat: add support for starknet treasuries and delegations

src/schemas/space.json
This PR fixes the error message for validation with `anyOf`, which were showing `Must match a schema in anyOf.`
This PR adds a more meaningful error message for validation using `anyOf`
=> fix: add meaninful error message for anyof validation

package.json, src/utils.ts, test/examples/space.json
Following on https://github.com/snapshot-labs/snapshot.js/pull/1069
This PR do not validate starknet testnet on mainnet, like for the regular network selector
=> fix: filter out starknet testnet on mainnet

package.json, src/schemas/space.json
This PR change the delegation network to be optional (will set a default on sequencer before saving)
=> fix: make delegationNetwork optional

src/schemas/space.json, src/utils.ts, test/examples/space-starknet-delegation.json
Related to https://github.com/snapshot-labs/workflow/issues/253
Allow https in domain 
- Run `yarn test`
- Edit test/examples/space.json with different domain values
=> fix: Allow https in domain

src/utils.ts
Continued from https://github.com/snapshot-labs/snapshot.js/pull/1074
- Run `yarn test`
- Edit `test/examples/space.json` with different domain values
=> fix: Allow slash at domain end

package.json, src/schemas/vote.json
Towards https://github.com/snapshot-labs/workflow/issues/260
- Increase Vote's `reason` max length to 5000.
=> feat: increase vote reason length to 5000

package.json, src/schemas/space.json, test/examples/space.json
Towards https://github.com/snapshot-labs/workflow/issues/275
- Add new fields  `discussionLink` and `discourseCategory` to space
- Run `yarn test` 
- change values in `test/examples/space.json`
=> feat: add discussion link and discourse category to space schema

src/schemas/proposal.json, src/schemas/vote.json
Reverting of https://github.com/snapshot-labs/snapshot.js/pull/1077
Reverting the length increase, as not easily feasible on the database side, see https://github.com/snapshot-labs/snapshot-sequencer/pull/463
=> revert: reverting app length increase

src/networks.json
Updated Klaytn network details to Kaia
- As part of rebranding the name of KLAY has been changed to KAIA. Please refer to below details
- https://www.binance.com/en/support/announcement/binance-will-support-the-kaia-klay-rebranding-to-kaia-kaia-f75f933759ee49d0af1dfbce7e32144c
- https://docs.kaia.io/references/public-en/#useful-resources
=> Updated klaytn to kaia network

src/schemas/space.json
Fixes https://github.com/snapshot-labs/sx-monorepo/issues/1098
This PR will make the `symbol` property optional in the space settings (and allow blank VO symbol)
=> feat: make symbol optional

scripts/addNetwork.ts, src/networks.json, test/e2e/network.spec.ts
Fixes https://github.com/snapshot-labs/workflow/issues/403
- Removes hash at end of existing URLs
- Avoids on new networks
- Add new test case
=> fix: remove extra hash in explorer URL

src/schemas/space.json
This PR will make the symbol property on Space truly optional, by removing the min length validation
=> fix: remove min length validation from space symbol

src/schemas/space.json
Toward https://github.com/snapshot-labs/workflow/issues/416
Depends on https://github.com/snapshot-labs/snapshot.js/pull/1119
This PR will add a new `logo` property to the `skinParams` object, to store white label custom logo
=> feat: add logo to skin params

package.json, src/schemas/space.json
Toward https://github.com/snapshot-labs/workflow/issues/418
This PR adds the skin colors to space schema
To be tested together with https://github.com/snapshot-labs/snapshot-sequencer/pull/497
=> feat: add skin colors to space settings

package.json, src/networks.json
- Change explorer to Mantlescan from https://explorer.mantle.xyz/ - current explorer tends to throw 404 for results and only shows data after refresh.
=> chore: update Mantle explorer to Mantlescan

package.json, src/utils.ts, test/e2e/utils.spec.js
Toward https://github.com/snapshot-labs/workflow/issues/523
This PR will return the space controller for .shib names, for both their mainnet and testnet.
~~As of now, they don't have an official api for returning name owner, it's using the same api service as their name service lookup (https://www.shibariumscan.io/name-domains)~~
PR updated to use d3 (their name partner) api to return names info.
=> feat: return space controller for .shib names

package.json, rollup.config.js, src/verify/index.ts, yarn.lock
Fixes https://github.com/stamp-labs/stamp/pull/371#issuecomment-2813197473
This PR will bump the starknet library to 6.11, to match the one used on sx and stamp.
This will also fix the memory overflow issue, when installed together with the `@webinterop/dns-connect`, which was resolved via https://github.com/starknet-io/starknet.js/commit/30a46815fa9fb88bbcb98df2f4a8dafc5a32b4ab#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L96
This version bump is causing some side effect, and is requiring some updates in the rollup config, since the `rollup-plugin-node-globals` package is 7 years old, and don't support optional chaining.
Tests are passing, and manual testing of the UMD build seems fine, can reproduce the issue mentioned in …
=> chore: update starknet dependency

src/utils.ts
Toward https://github.com/snapshot-labs/workflow/issues/562
This PR allows starknet addresses when calling `get_vp`, `validate` and `getScores`
=> feat: accept starknet address when fetching vp or validation

src/utils.ts
This PR loosen the starknet address validator, to accept both checksum (current) and lowercase (new) addresses as valid. It stil require that addresses are fully padded.,
This will align with the `evmAddress` validation, which is currently accepting both lowercase and checksum.
Without this patch, the validator will reject all checksum starknet address. In the ui side, we don't check for case when sending starknet address (like adding member in the space settings), so valid data on the UI will be rejected by sequencer.
=> fix: accept both lowercase and checksum starknet address as valid

package.json, src/schemas/space.json
Toward https://github.com/snapshot-labs/workflow/issues/565
Adds farcaster username to space profile
name validation from https://github.com/farcasterxyz/protocol/blob/main/docs/SPECIFICATION.md#5-fname-specifications : max 16 charaters, start by number or letter, and can only contain lowercase letter, number and hyphen
=> feat: add farcaster handle to space profile

package.json, src/networks.json, src/utils/provider.ts
Brovider is using a special string for starknet id (`sn`), which is not the chain id, like all the other networks.
We're currently using the `key` property to pass that for starknet, but it's not compatible with a lot of implementation, which is using `key` as chain ID.
This PR will add a new dedicated `broviderId` key, for networks having a custon brovider id, and fallback to the network id when missing. The `key` will be back to be the chain ID
=> fix: use a dedicated key for brovider id

package.json, src/utils.ts, test/e2e/utils.spec.js
Toward https://github.com/snapshot-labs/workflow/issues/598
This PR improves the .sonic domain name owner 
- now poll the registry for the owner, instead of the NFT contract (registry address not in the docs, obtained via direct contact with ud)
- function has been refactored to be future-proof, and ready to handle more chain/tld from unstoppable domains
Updated the test, since the `boorger.sonic` domain has now changed owner (EOA wallet, instead of UD custody wallet)
=> feat: return owner of .sonic domains (#1168)

src/voting/rankedChoice.ts
In ranked choice, getScoresByStrategy, the array can sometime contain `NaN`, when the choice is not present in the final round (sum a number with undefined)
Those NaN value are then passed to sequencer, who will then save it as null, giving scores column with `null` values in the proposals table, on the hub database
```sql
SELECT id, scores_by_strategy
FROM proposals
WHERE scores_by_strategy LIKE '%null%';
```
This fix will fallback missing score to 0
=> fix: fix NaN computation on ranked choice

package.json, src/voting/rankedChoice.ts
This PR fix an operator precedence issue, which was returning scores as 0 instead of the existing value, when summing with `undefined`
=> fix: fix operator precedence

src/voting/rankedChoice.spec.js, src/voting/rankedChoice.ts
This PR improves comprehension of the ranked choice voting system by adding more documentation, and add more test.
Add more docs to some function, to help comprehension, and understand returned value.
Add more tests, justifying that the fix https://github.com/snapshot-labs/snapshot.js/pull/1176 is really needed, and not just an edge case.
This fix is not related to invalid votes, etc..., the scenario can happen if the irv function pass on the first round, and the first round do no contain all the votes.
Update function to handle invalid choice: they're now ignored, instead of showing `undefined`, like on the approval/quadratic/weighted voting system. 
This is consistent with the score computation, where those invalid votes are already ignored
=> refactor: improve ranked choice voting readability and add test
