- src/strategies/index.ts
- src/strategies/moloch/index.ts
Fixes # .
- ad new strategy to get the number of shares from a moloch DAO
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bonustrack/snapshot.js/9)
> add moloch strategy

- src/strategies/index.ts
- src/strategies/synthetix/README.md
- src/strategies/synthetix/index.ts
Adds SNX strategy for vote weightings
- Quadratic voting
- Voters weight based on debt percentage at previous fee period
> add synthetix strategy

- src/strategies/cream-swap/index.ts
- src/strategies/index.ts
Add cream-swap strategy.
- Add cream-swap strategy.
- Fix strategy format in test.
> Add cream-swap strategy

- src/utils.ts
Fixes # .
- Add Wanchain Multicall contract address
- 
-
> Add Wanchain Multicall contract address

- src/plugins/aragon/index.ts
> Plugins: Update Aragon Govern plugin name

- src/plugins/aragon/index.ts
- Handle token approvals (if needed) on the Aragon Govern Plugin.
> Aragon Plugin: Handle token approvals

- src/plugins/aragon/index.ts
Kind of a silly but urgent fix 😅
> Aragon Plugin: Fix allowance call + addresses bug

- src/plugins/gnosis/index.ts
Add `getTokenPairWithWETH` to get tokens pairs based on `WETH` token.
If the given query token pair `token0-token1` does not exists on Uniswap-v2, the `getUniswapPair` will ask for the priceToken based on the two `WETH` pairs.
> Add query Uniswap v2 token pairs with WETH

- src/strategies/index.ts
- src/strategies/pancake/README.md
- src/strategies/pancake/index.ts
- add masterChef pool for strategy
> feat: update pancake strategy

- src/plugins/gnosis/index.ts
Fixes https://github.com/gnosis/snapshot.js/issues/2, https://github.com/gnosis/snapshot.js/issues/3
- Add multicall for 'name' and 'symbol' methods ERC-20 smart contract on one call.
- Improve GQL with `__aliasFor` to get different pairs from Uniswap-v2 in
one call.
> Replace call to multicall

- src/plugins/gnosis/index.ts
Reverts snapshot-labs/snapshot.js#49
> Revert "Replace call to multicall"

- src/networks.json
Fixes # .
- Add Thundercore mainnet to networks.json
- 
-
> Add Thundercore Mainnet

- src/strategies/index.ts
- src/strategies/xdai-stake/examples.json
- src/strategies/xdai-stake/index.ts
- src/strategies/xdai-stake/utils.ts
- src/utils/web3.ts
- added a strategy that calculates the user's voting power based on the balance of STAKE tokens and the amount of tokens deposited on EasyStaking together with the accrued emission
> Add xDai STAKE strategy

- src/strategies/defidollar/examples.json
- src/strategies/defidollar/index.ts
- src/strategies/index.ts
- test/index.ts
- Adds token balances across [DefiDollar](http://dusd.finance/) farming pools.
> DefiDollar Strategy

- package.json
- rollup.config.js
> Fix for import Snapshot.js give empty object

- src/networks.json
Fixes # .
- 
- Add POA Core mainnet to networks.json
-
> Add POA Core Network

- src/networks.json
[Docs](https://howto.xinfin.org/general/networks/)
-  [x] Add XinFin Network 
**sorry about my vscode prettier
> feat(networks): add XinFin Network

- src/strategies/cream/examples.json
- src/strategies/cream/index.ts
- Removes Cream swap score
- Add Sushiswap LP score
- Add CREAM supplied in Cream Lending
- Implement time weighted average balance
> Update cream strategy

- src/strategies/dittomoney/examples.json
- src/strategies/dittomoney/index.ts
```
npm run test --strategy=dittomoney
```
```log
> @snapshot-labs/snapshot.js@0.1.2 test
> node test/index.ts
Strategy: "dittomoney"
Ditto.money
[
{
'0x05ff2b0db69458a0750badebc4f9e13add608c7f': 0,
'0xd1a8Dd23e356B9fAE27dF5DeF9ea025A602EC81e': 0,
'0x48f7cb174a2333de834452ad240ce8d3d827dc55': 0,
'0x0d3cae1ff719d6a2ac0fcd7cd22f599cac64b6ec': 0.000001447498640604,
'0xE0e710A907a8E44c078e6212Efa336C1191F4CD1': 0
}
]
````
> chore(strategies): fixed loading error ditto.money 

- src/strategies/index.ts
- src/strategies/typhoon/examples.json
- src/strategies/typhoon/index.ts
- Adds typhoon strategy to read all farming pools token balance
- Adds an example.json file to test locally
> Add typhoon strategy

- src/strategies/index.ts
- src/strategies/xdai-stake-delegation/examples.json
- src/strategies/xdai-stake-delegation/index.ts
> Add xdai-stake-delegation strategy

- src/strategies/erc20-balance-of-with-min/examples.json
- src/strategies/erc20-balance-of-with-min/index.ts
- src/strategies/index.ts
- If balance is below minimum the voting power is replaces with zero
-
> Add balance-with-min strategy

- src/strategies/index.ts
- src/strategies/opium/examples.json
- src/strategies/opium/index.ts
- $OPIUM balance
- $wOPIUM balance
- 1inch LP OPIUM-ETH balance (adjusted to $OPIUM held in LP tokens)
- Farming 1inch LP OPIUM-ETH balance (adjusted to $OPIUM held in LP tokens)
> Add Opium strategy

- src/strategies/index.ts
- src/strategies/the-graph-grt/balances.ts
- src/strategies/the-graph-grt/delegators.ts
- src/strategies/the-graph-grt/examples.json
- src/strategies/the-graph-grt/index.ts
- src/strategies/the-graph-grt/indexers.ts
- src/strategies/the-graph-grt/tokenLockWallets.ts
- src/strategies/the-graph-grt/utils.ts
- Adds a strategy for Graph Token
> Graph token

- src/plugins/gnosis/index.ts
Add xDai thegraph Omen and HoneySwap API endpoints for support with
prediction markets on xDai network.
> Add xDai support on Gnosis Impact plugin

- src/strategies/pancake/index.ts
> update pancake swap strategy

- src/strategies/the-graph-balance/balances.ts
- src/strategies/the-graph-balance/examples.json
- src/strategies/the-graph-delegation/delegators.ts
- src/strategies/the-graph-delegation/examples.json
- src/strategies/the-graph-indexing/examples.json
- src/strategies/the-graph-indexing/indexers.ts
- src/strategies/the-graph/baseStrategy.ts
- src/strategies/the-graph/graphUtils.ts
- src/strategies/the-graph/tokenLockWallets.ts
This adds testing for the strategies into the repo.
I delegated and indexed specific amounts in the network, so I knew what the results would have to be. Then added into the `example.json`s the correct values to expect. Caught a few bugs along the way, but now everything checks out.
> Robust grt testing

- src/networks.json
- add fantom network mainnet configuration in networks.json
> add fantom network mainnet configuration

- src/networks.json
Fixes RPC Node issues in aavegotchi proposal
> Matic Network Node change from maticvigil

- package-lock.json
- package.json
- src/strategies/ens-reverse-record/README.md
- src/strategies/ens-reverse-record/examples.json
- src/strategies/ens-reverse-record/index.ts
- src/strategies/index.ts
This strategy allows you to vote if you set both forward and reverse ENS record on your ETH address.
> Ens reverse record

- src/strategies/cream/index.ts
> Snapshot build fail issue

- tsconfig.json
> Fix to show errors white running tests

- src/strategies/cream/examples.json
- src/strategies/cream/index.ts
Fixes too many request on CREAM strategy
- separate several multicaller to handle large amount calls
> Fix multicall bandwidth issue on CREAM strategy

- src/schemas/space.json
Fixes https://github.com/snapshot-labs/snapshot/issues/293
> fix: Allow dashes in social usernames

- src/strategies/index.ts
- src/strategies/masterchef-pool-balance/examples.json
- src/strategies/masterchef-pool-balance/index.ts
Generic strategy for voting with tokens staked in a masterchef type contract. Happy to discuss the details if not clear from the source code.
> Added masterchef-pool-balance strategy

- src/schemas/space.json
Add schema for admins field and add string length and pattern requirements.
Related to https://github.com/snapshot-labs/snapshot/pull/339
> Add schema for admins field

- src/strategies/apescape/examples.json
- src/strategies/apescape/index.ts
- src/strategies/index.ts
Custom strategy for apescape.eth project. Sums ROKT tokens staked in
pools
Thanks!
> Added APEscape strategy

- .github/workflows/strategy.yml
- test/index.ts
To execute this action, the following conditions should be satisfied:
- A PR should have a title with strategy name within brackets `[]`
example: `Change strategy [eth-wallet-age]`
- Should add a `strategy` label to PR
Example PR: [pull request on ChaituVR's fork to show how it works](https://github.com/ChaituVR/snapshot.js/pull/5)
> Run Github Actions to test strategy within PR itself 

- src/strategies/governor-alpha/examples.json
- src/strategies/governor-alpha/index.ts
- src/strategies/index.ts
> [governor-alpha] Governor alpha strategy

- src/plugins/safeSnap/index.ts
Quick fix to rename SafeSnap plugin.
> safesnap: Rename plugin

- src/networks.json
https://twitter.com/0xPolygon/status/1402590551619162116
> Polygon explorer

- src/networks.json
- src/strategies/eth-balance/index.ts
- src/utils.ts
> Move multicall addresses to networks.json

- src/strategies/cake/README.md
- src/strategies/cake/examples.json
- src/strategies/cake/index.ts
- src/strategies/index.ts
Adds a new strategy for PancakeSwap.
> [cake] PancakeSwap Strategy/cake

- src/utils/contentHash.ts
> Fix ABI format

- src/strategies/index.ts
- src/strategies/iotex-staked-balance/examples.json
- src/strategies/iotex-staked-balance/index.ts
add strategy iotex-staked-balance
> Add strategy [iotex-staked-balance]

- src/strategies/impossible-finance/examples.json
- src/strategies/impossible-finance/index.ts
updated weighting system for gov tokens in LP (set 20% vote weight bonus for underlying IF tokens in all LP pools)
> [impossible-finance] Impossible strategy

- test/index.spec.ts
> Test returned addresses should be either same case as input addresses or checksum addresses

- src/strategies/index.ts
- src/strategies/unipool-same-token/examples.json
- src/strategies/unipool-same-token/index.ts
Generic strategy for UniPool contract where the staked token equals the earned token
> [unipool-same-token] Add unipool-same-token strategy

- src/strategies/index.ts
- src/strategies/tomb-finance/examples.json
- src/strategies/tomb-finance/index.ts
New voting strategy for tomb.finance
Calculates the amount of TShares in:
user's wallet
LP in user's wallet
LP in Cemetery TSHARE-FTM LP pool
Masonry single-staking pool
auto-compounding vaults of TSHARE-FTM LP
As we are using the quadratic voting, to calculate the amount of votes the Math.sqrt() is used on the total amount of owned TShares.
> [tomb-finance] New strategy for tomb.finance

- src/strategies/aavegotchi/examples.json
- src/strategies/aavegotchi/index.ts
Reverts snapshot-labs/snapshot.js#323
> Revert "[aavegotchi] update strategy to add ghstweth pool power"

- src/strategies/tomb-finance/index.ts
Fix the wrong precision calculation in the Tomb Finance strategy.
> [tomb-finance] Fix tomb-finance strategy precision

- src/strategies/tomb-finance/index.ts
Remove unused import from Tomb Finance strategy.
> [tomb-finance] Remove unused import

- src/strategies/decentraland-estate-size/index.ts
https://snapshot.org/#/snapshot.dcl.eth/proposal/QmZZx6pThLnKfWGd5t4ujYha7PLWMqu98mtt1MtxpZgPJ3
> [decentraland-estate-size] Fix decentraland-estate-size block issue

- src/networks.json
⚠️ We've moved the voting strategies to another repository, if you want to add or edit strategy you must do it here: https://github.com/snapshot-labs/snapshot-strategies
> Avalanche chain id fix

- package-lock.json
- package.json
⚠️ We've moved the voting strategies to another repository, if you want to add or edit strategy you must do it here: https://github.com/snapshot-labs/snapshot-strategies
> Set Version 0.2.8

- src/utils/provider.ts
Needed to add batching for https://github.com/snapshot-labs/snapshot/issues/680
> feat(): add a batching provider

- src/networks.json
⚠️ We've moved the voting strategies to another repository, if you want to add or edit strategy you must do it here: https://github.com/snapshot-labs/snapshot-strategies
> Disable Arbitrum network

- src/schemas/space.json
For https://github.com/snapshot-labs/snapshot/pull/815
> Add schema for voting delay and period

- package-lock.json
- package.json
- src/sign/index.ts
Fixes https://github.com/snapshot-labs/snapshot-hub/issues/158
> Fix timestamp floor issue

- src/networks.json
> Add back Arbitrum network

- src/schemas/space.json
⚠️ We've moved the voting strategies to another repository, if you want to add or edit strategy you must do it here: https://github.com/snapshot-labs/snapshot-strategies
> feat: add 'blind' property

- src/validations/index.ts
- src/validations/nouns/examples.json
- src/validations/nouns/index.ts
_Changes proposed in this pull request:_
- add Nouns Space validation function for validation of new proposals.
> Nouns Space Validation

- src/voting/rankedChoice.ts
There was a bug with the strategy calculation when the proposal only had a single strategy.
> Fix ranked choice bug with single strategy

- src/schemas/space.json
See: https://github.com/snapshot-labs/snapshot/pull/1124
> added hideAbstain parameter to space schema

- .github/workflows/npm-publish.yml
> Fix package publish workflow

- src/utils.ts
Related to https://github.com/snapshot-labs/snapshot/issues/1582
> feat(): added more subgraphs

- .github/workflows/npm-publish.yml
As suggested in https://github.com/snapshot-labs/lock/pull/38
> Remove duplicate build and yarn install from lockfile

- package.json
- src/networks.json
Code to prove that I haven't changed anything from the object
https://runkit.com/chaituvr/check-networks-json-is-same-as-master
> Format networks.json file

- package.json
- src/utils.ts
https://github.com/snapshot-labs/snapshot-subgraph/pull/4
> Fantom subgraph

- package.json
- src/networks.json
https://twitter.com/MoonriverNW/status/1496636540969177090
https://discord.com/channels/707079246388133940/747049240022482974/946716671366823936
> Update Moonriver node

- src/networks.json
> Add HPB Mainnet Support

- src/networks.json
XinFin XDC.Network is an enterprise-ready hybrid Blockchain technology company optimised for international trade and finance. The XinFin XDC.network is powered by the native coin called XDC. The XDC protocol is architected to support smart contracts, 2000TPS, 2 seconds transaction time, KYC to Masternodes (Validator Nodes). The XDC.Network uses XinFin Delegated Proof of Stake (XDPoS), with the intending to create a ‘highly-scalable, secure, permission, and commercial grade’ blockchain network.
Github:- https://github.com/XinFinOrg
CMC :- https://coinmarketcap.com/currencies/xinfin-network/
Docker FullNode:- https://github.com/xinfinorg/XinFin-Node
Technical Community Support available at:
Telegram Community: https://t.me/XinFinDevelopers
Slack Community: …
> Add Support for XinFin ( XDC ) Network.

- package.json
- src/utils.ts
Fixes #539 
Fixes https://github.com/snapshot-labs/snapshot-hub/issues/280
> Decentralized Subgraph

- package.json
- src/utils.ts
Related to https://github.com/snapshot-labs/snapshot/issues/2156
> Get delegates by space function

- src/schemas/index.ts
- src/schemas/profile.json
- test/examples/profile.json
- test/schema.ts
> feat(): added profile schema

- package.json
- src/schemas/profile.json
- test/examples/profile.json
@samuveth removed twitter. It did not require changes to types so we are good.
> Remove twitter

- package.json
- src/schemas/profile.json
@samuveth you should now be able to use this one.
> fix(): use customUrl format

- src/networks.json
> add ontology network

- src/networks.json
Fixes https://github.com/snapshot-labs/snapshot.js/issues/525
> imageIPFS to logo

- src/networks.json
add cubechain testnet information
> add Cube testnet

- src/networks.json
Fixes # .
- add KardiaChain Mainnet network
- add KardiaChain Testnet network
> add network kardiachain mainnet

- src/networks.json
Adds support for Candle chain on snapshot.
- addition of a new network (candle)  
- 
-
> Update networks.json - Add Candle

- package.json
- src/networks.json
Fixes # .
- added klaytn mainnet configuration to network.json
> add klaytn mainnet

- src/networks.json
> add cube mainnet

- package.json
- src/utils/provider.ts
Related to https://github.com/snapshot-labs/snapshot/issues/2492
> Use brovider

- package.json
- src/sign/eip1271.ts
- src/utils.ts
- test/multicaller.ts
Related to https://github.com/snapshot-labs/snapshot/issues/2492
> Use brovider for ENS text record, eip1271 verify and multicall test file

- package.json
- src/voting/approval.ts
- src/voting/quadratic.ts
- src/voting/rankedChoice.ts
- src/voting/singleChoice.ts
- src/voting/weighted.ts
- Move `isValidChoice` into the voting class
> Refactor voting

- src/networks.json
Additions # .
- Add Nova Network
> add nova network

- package.json
- src/networks.json
- Add "Wennect Testnet" network
> add Wennect Testnet network

- src/schemas/space.json
This PR add schema to define who can follow a space and cast a vote using validation strategies.
> Add vote and follow validations

- src/networks.json
Add PHI Network Smart Chain 
https://chainlist.org/chain/144
Fixes # .
- 
- 
-
> ADD PHI Network

- src/voting/quadratic.spec.js
- src/voting/quadratic.ts
- src/voting/weighted.spec.js
- src/voting/weighted.ts
https://discord.com/channels/707079246388133940/817492434636111977/1009873282117410917
> Check if atleast one choice is positive in weighted and quadratic voting

- package.json
- src/networks.json
Fixes # .
- added palm tesnet
- 
-
> Adding Palm Testnet

- package.json
- src/networks.json
Fixes # .
-  Add Dogechain
- 
-
> Add Dogechain network

- package.json
- src/networks.json
* Add DXC network
* Update src/networks.json
> Add DXC network

- src/networks.json
- Add support for Razor SKALE Chain
> Add Razor SKALE Chain

- package.json
- src/networks.json
Fixes # .
- Add Public Mint network to the list of supported chains.
- 
-
> Add PublicMint network

- src/networks.json
Update ThunderCore network config
> update thundercore network

- package.json
- src/networks.json
Fixes # .
- Update the Public Mint logo ipfs file path
- 
-
> Update Public Mint logo

- src/networks.json
> Adding DynoChain

- src/networks.json
- Add Flare Mainnet (https://chainlist.org/chain/14)
- Add Flare Testnet Coston (https://chainlist.org/chain/16)
- Add Songbird Canary-Network (https://chainlist.org/chain/19)
> Add Flare related networks

- src/networks.json
- Add support for Anytype EVM network
Thank you very much! You are building an awesome product!
> Add Anytype EVM network to networks.json

- package.json
- src/networks.json
Fixes https://github.com/snapshot-labs/snapshot/issues/3200
> Remove support for Rinkeby, Kovan and Ropsten

- package.json
- src/networks.json
> Add posichain mainnet

- package.json
- src/networks.json
Fixes # .
- Add support for GodwokenV1 EVM networks (mainnet and testnet)
> Add GodwokenV1 Networks

- package.json
- src/networks.json
- Add canto network (https://chainlist.org/chain/7700)
> Add canto network

- src/networks.json
Add Qitmeer chain
Fixes # .
- Add support for Qitmeer EVM mainnet networks
- 
-
> Add Qitmeer chain

- src/networks.json
> Add Exosama Network 

- src/networks.json
Signed-off-by: recursivethedev <recursivethedev@gmail.com>
Fixes # .
- 
- 
Hey Everyone, we would like to add our testnet chain to snapshot and start using it.
I hope you guys merge this one as soon as possible. 
We are so exited.
> New Network Addition Request - Cascadia

- package.json
- src/networks.json
> add: step network

- src/networks.json
> Add SX Network Testnet

- src/networks.json
Fixes # .
-  Add Redlight Main chain
- 
-
> Add Redlight Chain

- src/networks.json
- Added a new network to networks.json
> Added Base Goerli Testnet on networks.json

- src/utils.ts
Related to https://github.com/snapshot-labs/snapshot/issues/3472
Add `getEnsOwner` and `getSpaceController` helper functions for Ui and Hub.
> feat: Add get owner and controller helpers

- package.json
- src/constants.json
- src/sign/index.ts
It is hard to use the local hub and sequencer in UI
> Using local hub and sequencer

- package.json
- src/voting/approval.spec.js
- src/voting/approval.ts
- src/voting/examples/rankedChoice.json
- src/voting/quadratic.spec.js
- src/voting/quadratic.ts
- src/voting/rankedChoice.spec.js
- src/voting/rankedChoice.ts
- src/voting/singleChoice.spec.js
- src/voting/singleChoice.ts
- src/voting/weighted.spec.js
- src/voting/weighted.ts
Related to https://github.com/snapshot-labs/snapshot-sequencer/pull/23
> Count all votes to scoresTotal

- package.json
- src/utils.ts
Alternative to https://github.com/snapshot-labs/snapshot.js/pull/565
> Add new option for limit

- package.json
- src/networks.json
Fixes # .
- Updated the working archive nodes of klaytn (Reference: https://docs.klaytn.foundation/content/dapp/json-rpc/public-en)
> Updated Working Klaytn RPC Archive Endpoints

- src/networks.json
> Added ShimmerEVM testnet in networks.json

- src/networks.json
Fixes # .
- remove old nahmii testnet details
- add new nahmii testnet details
-
> fix: nahmii testnet details

- package.json
- src/networks.json
- src/utils.ts
More details:
https://discord.com/channels/955773041898573854/1030772384308932608/1101096623699935282
> Fallback to ensNameWrapper

- package.json
- src/networks.json
> Add Horizen Gobi Testnet

- package.json
- src/networks.json
> - add arbitrum nova

- src/networks.json
> add ENULS network

- package.json
- src/networks.json
add network: Metis Testnet (599)
> Update networks.json with metis testnet

- package.json
- src/networks.json
- src/utils.ts
> Multiple ENS resolvers

- src/networks.json
this is a Emergency update, the qitmeer rpc connection error, need add new rpc
Fixes # .
- 
- 
-
> fix qitmeer rpc

- src/networks.json
Fixes # .
- Chain Verse Mainnet added to network.json
- Space in the name "Chain Verse"
> Added Chain Verse Mainnet to network.json

- package.json
- src/schemas/space.json
Reverts snapshot-labs/snapshot.js#837
> Revert "feat: Add space delegation portal schema"

- src/networks.json
> fix core chain scan path

- src/networks.json
Fixes # .
- adds Taraxa testnet to Snapshot
- adds Taraxa mainnet to Snapshot
-
> Adds Taraxa mainnet and testnet

- src/networks.json
> Updated Cascadia network

- src/networks.json
Add Pulsechain network
- 
- 
-
> Add Pulsechain network

- src/networks.json
Fixes #863  .
- Add Arthera network logo
- Add Arthera testnet network RPC details
- Add Arthera testnet network contract address
> Add Arthera testnet network support

- src/networks.json
- Add zkSync Era Mainnet to network list
> Add zksync era mainnet

- .github/workflows/test.yml
- .gitignore
- package.json
- yarn.lock
Test coverage are not currently tracked.
This PR will upload the test coverage after running the github actions test to codecov.
The organization is using https://app.codecov.io/gh/snapshot-labs to track all tests in one single place.
> chore: upload test coverage to codecov

- package.json
- src/networks.json
> Add EON Mainnet

- package.json
- src/utils.ts
- test/vp.ts
How to test?
Try running `ts-node test/vp.ts` and check the headers in requests
> API key in headers to score-api

- package.json
- src/sign/eip1271.ts
- src/sign/utils.ts
- src/utils.ts
- src/utils/blockfinder.ts
- src/utils/provider.ts
- add extra variables to functions for configuring hardcoded endpoints/data
- those variables are optional, so it should work the same way for our users
> feat(config): add ability to define brovider URL

- package.json
- src/schemas/statement.json
- test/examples/statement.json
We agreed on going back to minlength `1` to enable things like a single emoji
> fix: Change minlength about back to 1

- .github/workflows/test.yml
It is running twice on each pull request
> fix: Remove pull_request trigger for test action

- package.json
- src/schemas/alias.json
- src/schemas/index.ts
- test/examples/alias.json
- test/schema.spec.ts
Related to https://github.com/snapshot-labs/snapshot-sequencer/pull/189
We need to check if alias address is a valid address
> fix: Add schema for alias

- package.json
- src/networks.json
> Decimal chain name change

- src/networks.json
Update avatars of `24` , `1072`, `7341` and  `9001`
> fix: Update network avatars in networks.json

- src/utils.ts
> Add new Error() for input errors

- package.json
- src/constants.json
Change to new URL, More details: https://discord.com/channels/955773041898573854/1030772407226601522/1175036485842509884
> fix: update hub testnet URL

- src/networks.json
> fix: Remove thaichain and genechain

- src/networks.json
> fix core chain rpc url to archive node

- src/networks.json
Context: https://discord.com/channels/955773041898573854/1125390177888645231/1211638081292075019
We don't need the "Mainnet" suffix for networks
> fix: Remove mainnet sufix for all networks

- package.json
- src/networks.json
To keep track of subscirptions
> Add subscription field

- package.json
- src/networks.json
Reverts snapshot-labs/snapshot.js#965
> Revert "Add subscription field"

- package.json
- src/schemas/space.json
> fix(boost): Naming

- package.json
- src/networks.json
- Add ens resolvers and wrappers for sepolia network
- Add ensSubgraph field for mainnet, goerli and sepolia
> Add ens data for sepolia and add ens subgraph field

- package.json
- src/sign/index.ts
Fixes #972 
Pass `chainId` into payload for trust wallet
> Feat: Pass chain ID for trust wallet

- package.json
- src/schemas/proposal.json
Context: https://discord.com/channels/955773041898573854/1187762747614703628/1224512393342746655
Increase character limit for turbo to 40k
> Increase turbo chars limit

- package.json
- src/schemas/space.json
Related to https://github.com/snapshot-labs/snapshot/issues/4600 
Now we call it "quorum of rejection"
> fix: Change optimistic quorum to quorum of rejection

- package.json
- src/delegationSubgraphs.json
Waiting for https://github.com/snapshot-labs/snapshot-subgraph/pull/15
> Add sepolia delegation subgraph

- package.json
- src/sign/index.ts
Fixes
addresses https://github.com/snapshot-labs/snapshot.js/issues/992
-  added a check for window to avoid breaking node envs
> added a check for window to avoid breaking node envs

- package.json
- src/gateways.json
Fixes https://github.com/snapshot-labs/snapshot/issues/4796
Replaces rate limted gateway with new one
> fix: Replace cf gateway with 4everland

- src/verify/starknet.spec.ts
Update tests to reflect that starknet verification can verify on different chain
> chore: fix tests

- package.json
- src/networks.json
From https://discord.com/channels/955773041898573854/1031838169282392144/1285944252525711544
> fix: update ENS sepolia subgraph url

- package.json
- src/schemas/proposal.json
- src/schemas/vote.json
Toward https://github.com/snapshot-labs/workflow/issues/235
Discussion https://discord.com/channels/955773041898573854/1296435871431786587
Increase the max length of the proposal and vote property to 128
> feat: increase app max length

- package.json
- src/schemas/proposal.json
- src/schemas/space.json
- src/schemas/update-proposal.json
- src/sign/hashedTypes.json
- src/sign/types.ts
- test/examples/proposal.json
- test/examples/space.json
Reverts snapshot-labs/snapshot.js#1082
> Revert "feat: Add new privacy type"

- package.json
- src/networks.json
Reverts snapshot-labs/snapshot.js#1100
> Revert "Remove fantom from networks"

- package.json
- src/networks.json
Fixes # .
- Add network opBNB Testnet(5611)
> Add network opBNB Testnet

- package.json
- src/schemas/space.json
Related to https://github.com/snapshot-labs/sx-monorepo/pull/1122
> chore: add new categories

- src/sign/index.ts
- test/test.html
Fixes https://github.com/snapshot-labs/workflow/issues/454
> fix: create proposal doesn't work without labels param
